apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: pj1w4rhql-java-quarkus 
  janus-idp.io/tekton: pj1w4rhql-java-quarkus
  backstage.io/kubernetes-id: pj1w4rhql-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: pj1w4rhql-java-quarkus
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml