apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: pj1w4rhql-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/pj1w4rhql-java-quarkus-gitops